mailrun now monitors offlineimap differently
Before this patch we would check to see if offlineimap was running and
kill it if so, assuming it's a hung process. This led to a few occasions
where mailrun killed a manual sync I was doing from mutt.

This patch changes mailrun in stead babysit offlineimap for a minute,
killing it if it hasn't yet completed.

Now that we know an existing process can only come from a true sync, we
can exit ourselves when that's encountered and not kill things we
shouldn't.

diff --git a/bin/mailrun b/bin/mailrun
--- a/bin/mailrun
+++ b/bin/mailrun
@@ -1,9 +1,31 @@
 #!/bin/bash
+
+# offlineimap has some issue joining threads and will occasionally hang
+# indefinitely. this method checks every ten seconds if the process
+# identified as $1 is still running. after 5 checks (~60 seconds), it
+# kills it. non-zero return status indicates something killed.
+monitor() {
+  local pid=$1 i=0
+
+  while ps $pid &>/dev/null; do
+    ((i++))
+
+    if (( i > 5 )); then
+      echo "Max checks reached. Sending SIGKILL to ${pid}..." >&2
+      kill -9 $pid; return 1
+    fi
+
+    sleep 10
+  done
+
+  return 0
+}
+
 read -r pid < ~/.offlineimap/pid
 
 if ps $pid &>/dev/null; then
-  echo "offlineimap ($pid): another instance running." >&2
-  kill -9 $pid
+  echo "Process $pid already running. Exiting..." >&2
+  exit 1
 fi
 
-offlineimap -o -u quiet &
+offlineimap -o -u quiet & monitor $!
